src/main/java/entities/Product.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package entities;

import java.io.Serializable;
import Interfaces.*;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.List;
import java.util.Objects;
import javax.persistence.*;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import structures.AuctionLength;
import structures.Category;

/**
 *
 * @author grp3
 */
@Entity
@Table(name = "PRODUCT")
    @NamedQueries({
    @NamedQuery(name = "products.getAllInIncreasingEndsTimeAuctionorder", query = "SELECT p FROM Product p ORDER BY p.auction.endAuction ")})
@XmlRootElement
public class Product implements Serializable {

    private static final long serialVersionUID = 1L;
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;
    @Enumerated(EnumType.STRING)
    Category category;
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "pr_creation_date", 
        columnDefinition="TIMESTAMP DEFAULT CURRENT_TIMESTAMP")
    Date createdDate;
    private Features features;
    private String pictureURL;
    private float price;
    @Column(name = "PR_PRODDESC")
    private String productDescription;
    private String productName;
    private boolean hasPicture;
    @JoinColumn(name = "auction_fk")
    @OneToOne(cascade = CascadeType.ALL)
    Auction auction;
    @ManyToOne
    @JoinColumn(name = "CUSTOMER_FK" )
    Customer productPoster;
    @OneToMany(mappedBy = "bidedProduct",cascade = CascadeType.ALL)
    private List<Bid> allBids;
    
    public Product() {
        auction = new Auction();
    }
    @XmlTransient
    public Auction getAuction() {
        if (auction == null) {
            auction = new Auction();
        }
        return auction;
    }
    
    public void setAuction(Auction auction) {
        if (auction == null) {
            auction = new Auction();
        }
        this.auction = auction;
    }
    public void setAuction( Date start, Date end){
        if (auction == null) {
         auction = new Auction();
        }
        auction.setAuction(start,end, this);
    }

    public Date getCreatedDate() {
        return new Date();
    }
    public void setCreatedDate(Date date){
        this.createdDate = date;
    }
    @PrePersist
    public void createAt(){
        this.createdDate = new Date();
        
    }
    @XmlTransient
    public List<Bid> getAllBids() {
        if(allBids != null)
            return allBids;
        return new ArrayList<Bid>();
    }

    public void setAllBids(List<Bid> allBids) {
        this.allBids = allBids;
    }
    public void setNewBid(Bid bid, Customer customer){
        if (auction == null) {
            auction = new Auction();
        }
        bid.setBidedProduct(this);
        bid.setBidder(customer);
        auction.setCurrentBid(bid);
        this.price = bid.getBidValue();
        allBids.add(bid);
    }

    public float getPrice() {
        getHighestBid();
        return price;
    }
    public void getHighestBid() {

        if (allBids != null && !allBids.isEmpty()) {
            for (Bid bid : allBids) {
                float value = bid.getBidValue();
                if (price < value) {
                    price = value;
                }
            }

        }

    }

    public void setPrice(float price) {
        this.price = price;
    }
    @XmlTransient
    public Customer getProductPoster() {
        return productPoster;
    }

    public void setProductPoster(Customer productPoster) {
        this.productPoster = productPoster;
    }
    
    public List<Category> getAllCategories(){
        return Arrays.asList(Category.values());
    }
    

    public Category getCategory() {
        return category;
    }

    public void setCategory(Category category) {
        this.category = category;
    }


    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }
    public String getProductName(){
        return this.productName;
    }
    public void setProductName(String name){
        this.productName = name;
    }
    public String getPictureURL(){
        if (pictureURL == null) {
            return "noimage.jpg";
        }
        return this.pictureURL;
    }
    public void setPictureUrl(String picture){
        
        this.pictureURL = picture;
    }

    public boolean isHasPicture() {
        return hasPicture;
    }

    public void setHasPicture(boolean hasPicture) {
        this.hasPicture = hasPicture;
    }
  
    public String getProductDescription(){
        return this.productDescription;
    }
    public void setProductDescription(String description){
        this.productDescription = description;
    }
    public Features getFeatures(){
        return this.features;
    }
    public void setFeature(Features features){
        this.features = features;
    }
    public List<AuctionLength> getAllAuctionLengths(){
        return Arrays.asList(AuctionLength.values());
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 23 * hash + Objects.hashCode(this.id);
        hash = 23 * hash + Objects.hashCode(this.productName);
        hash = 23 * hash + Objects.hashCode(this.pictureURL);
        hash = 23 * hash + Objects.hashCode(this.productDescription);
        hash = 23 * hash + Objects.hashCode(this.features);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Product other = (Product) obj;
        if (!Objects.equals(this.productName, other.productName)) {
            return false;
        }
        if (!Objects.equals(this.pictureURL, other.pictureURL)) {
            return false;
        }
        if (!Objects.equals(this.productDescription, other.productDescription)) {
            return false;
        }
        if (!Objects.equals(this.id, other.id)) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "Product{" + "id=" + id + ", owner=" + productPoster + ", auction=" + auction + ", productDescription=" + productDescription + /*", features=" + features */ '}';
    }
}

src/main/java/mangedBeans/controller/ProductController.java
package mangedBeans.controller;

import entities.Product;
import Interfaces.util.JsfUtil;
import Interfaces.util.JsfUtil.PersistAction;
import boundary.AuctionFacade;
import boundary.ProductFacade;
import entities.Auction;
import entities.Customer;
import java.io.File;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.io.OutputStream;

import java.io.Serializable;
import java.util.List;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.ejb.EJB;
import javax.ejb.EJBException;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.application.FacesMessage;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.servlet.ServletContext;
import org.primefaces.event.FileUploadEvent;
import org.primefaces.event.FlowEvent;
import org.primefaces.model.UploadedFile;

@Named("productController")
@SessionScoped
public class ProductController implements Serializable {

    @EJB
    private ProductFacade ejbFacade;
    @EJB
    AuctionFacade af;
    private List<Product> items = null;
    private Product selected;
    private long prodId;
    private Customer owner;
    private boolean skip;
    public ProductController() {
    }

    public long getProdId() {
        return prodId;
    }

    public Customer getOwner() {
        return owner;
    }

    public void setOwner(Customer owner) {
        this.owner = owner;
    }

    public void setProdId(long prodId) {
        this.prodId = prodId;
    }
    public Product getPrFromId(){
        
     return getProduct(prodId);
    
    }
 
    public Product getSelected() {
        return selected;
    }

    public void setSelected(Product selected) {
        this.selected = selected;
    }

    protected void setEmbeddableKeys() {
    }

    protected void initializeEmbeddableKey() {
    }

    private ProductFacade getFacade() {
        return ejbFacade;
    }

    public Product prepareCreate() {
        selected = new Product();
        
        initializeEmbeddableKey();
        return selected;
    }

    public void create() {
        selected.setAuction(new Auction());
        selected.setProductPoster(owner);
        persist(PersistAction.CREATE, ResourceBundle.getBundle("/Bundle").getString("ProductCreated"));
        if (!JsfUtil.isValidationFailed()) {
            items = null;    // Invalidate list of items to trigger re-query.
        }
    }

    public void update() {
        persist(PersistAction.UPDATE, ResourceBundle.getBundle("/Bundle").getString("ProductUpdated"));
    }

    public void destroy() {
        persist(PersistAction.DELETE, ResourceBundle.getBundle("/Bundle").getString("ProductDeleted"));
        if (!JsfUtil.isValidationFailed()) {
            owner.getProductList().remove(selected);
            selected = null; // Remove selection
            items = null;    // Invalidate list of items to trigger re-query.
        }
    }

    public List<Product> getItems() {
        items = getFacade().getAllProductsOrdered(owner.getId());
        return items;
    }

    private void persist(PersistAction persistAction, String successMessage) {
        if (selected != null) {
            setEmbeddableKeys();
            try {
                if (persistAction != PersistAction.DELETE) {
                    getFacade().edit(selected);
                    items.add(selected);
                    owner.setProductList(items);
                } else {
                    getFacade().remove(selected);
                    af.remove(selected.getAuction());
                    
                }
                JsfUtil.addSuccessMessage(successMessage);
            }
            catch (EJBException ex) {
                String msg = "";
                Throwable cause = ex.getCause();
                if (cause != null) {
                    msg = cause.getLocalizedMessage();
                }
                if (msg.length() > 0) {
                    JsfUtil.addErrorMessage(msg);
                } else {
                    JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
                }
            } catch (Exception ex) {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, null, ex);
                JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            }
        }
    }

    public Product getProduct(java.lang.Long id) {
        return getFacade().find(id);
    }

    public List<Product> getItemsAvailableSelectMany() {
        return getFacade().findAll();
    }

    public List<Product> getItemsAvailableSelectOne() {
        return getFacade().findAll();
    }

    @FacesConverter(forClass = Product.class)
    public static class ProductControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            ProductController controller = (ProductController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "productController");
            return controller.getProduct(getKey(value));
        }

        java.lang.Long getKey(String value) {
            java.lang.Long key;
            key = Long.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Long value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Product) {
                Product o = (Product) object;
                return getStringKey(o.getId());
            } else {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, "object {0} is of type {1}; expected type: {2}", new Object[]{object, object.getClass().getName(), Product.class.getName()});
                return null;
            }
        }

    }
    public String seePostedProducts(){
        return "/product/crud/List";
    }
     public boolean isSkip() {
        return skip;
    }
 
    public void setSkip(boolean skip) {
        this.skip = skip;
    }
     
    public String onFlowProcess(FlowEvent event) {
        if(skip) {
            skip = false;   //reset in case user goes back
            return "confirm";
        }
        else {
            return event.getNewStep();
        }
    }
        /**
     * Upload a file from jsf
     * @param event 
     */
    public void fileUpload(FileUploadEvent event){
        FacesMessage message = new FacesMessage("Succesful", event.getFile().getFileName() + " is uploaded.");
        FacesContext.getCurrentInstance().addMessage(null, message);
        String img = saveFile(event.getFile());
        selected.setPictureUrl(img);
        selected.setHasPicture(true);
        System.out.println("uploaded: " + img);
           
    }
        /**
     * Save an uploaded picture to the resources folder in the project.
     * @param event
     * @return 
     */
    private String saveFile(UploadedFile image){
        String uploaded = "";
        try{
            String filename = image.getFileName();
            try (InputStream input = image.getInputstream()) {
                ServletContext ctx = (ServletContext) FacesContext.getCurrentInstance()
                        .getExternalContext().getContext();
                String realPath = ctx.getRealPath("/");
                String imgFolderPath = realPath.substring(0, realPath.length()-35) + "src" + File.separatorChar +  "main" + File.separatorChar + "webapp" + File.separatorChar +
                        "resources" + File.separatorChar + "images" + File.separatorChar + "productimg" + File.separatorChar;
                File file = new File(imgFolderPath, filename);
                int i = 0;
                while(file.exists()){
                    int ind = filename.lastIndexOf('.');
                    String name = filename.substring(0,ind);
                    String ext = filename.substring(ind, filename.length());
                    file = new File(imgFolderPath, name + "(" + i++ + ")" + ext);
                }
                uploaded = file.getName();
                try (OutputStream output = new FileOutputStream(file)) {
                    int read;
                    byte [] bytes = new byte[1024];
                    while((read = input.read(bytes)) != -1){
                        output.write(bytes, 0 , read);
                    }
                }
            }
        }
        catch(Exception e){
            System.out.println("Problemer saving file: " + e.getMessage());
        }
        return uploaded;
    }
}

src/main/webapp/product/crud/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="ProductCreateDlg" style="width: 610px " widgetVar="ProductCreateDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.CreateProductTitle}">
            <h:form id="ProductCreateForm">
                <p:wizard flowListener="#{productController.onFlowProcess}">
                    <p:tab id="general" title="General">
                        <p:panel header="General Details">
                            <p:messages />
                            <h:panelGroup id="display">
                                <p:panelGrid columns="2" rendered="#{productController.selected != null}">
                                    <p:outputLabel value="#{bundle.CreateProductLabel_category}" for="category" />
                                    <p:selectOneMenu id="category" value="#{productController.selected.category}" >
                                        <f:selectItems value="#{productController.selected.allCategories}"
                                                       var="categoryItem"
                                                       itemValue="#{categoryItem}"/>
                                    </p:selectOneMenu>
                                    <p:outputLabel value="Productname: " for="productname" />
                                    <p:inputText id="productname" required="true" value="#{productController.selected.productName}" title="#{bundle.CreateProductTitle_productname}" />
                                                                    <p:outputLabel value="#{bundle.CreateProductLabel_createdDate}" for="createdDate" />
                                <p:calendar id="createdDate" disabled="true" pattern="MM/dd/yyyy HH:mm:ss" value="#{productController.selected.createdDate}" title="#{bundle.EditProductTitle_createdDate}"  navigator="true" mask="true"  />
                                <p:outputLabel value="#{bundle.CreateProductLabel_price}" for="price" />
                                <p:inputText id="price" value="#{productController.selected.price}" title="#{bundle.CreateProductTitle_price}">
                                    <p:slider for="price" maxValue="1000" />
                                </p:inputText>
                                </p:panelGrid>
                            </h:panelGroup>
                        </p:panel>
                    </p:tab>

                    <p:tab id="productinfo" title="Product description">
                        <p:panel header="Describe your product">
                            <p:messages />
                            <h:panelGrid columns="2" columnClasses="label, value">
                                <p:inputTextarea id="productDescription"
                         rows="10"
                         cols="70"
                         counter="displayCounter"
                         maxlength="1000" 
                         counterTemplate="{0} characters remaining" 
                         value="#{productController.selected.productDescription}" 
                         title="#{bundle.CreateProductTitle_productDescription}" /><br/>
                                <h:outputText id="displayCounter"/>

                            </h:panelGrid>
                        </p:panel>
                    </p:tab>

                    <p:tab id="imageupload" title="Image upload">
                        <p:panel header="Upload productimage">
                            <p:messages />

                            <p:fileUpload fileUploadListener="#{productController.fileUpload}" style="width: 550px" mode="advanced" dragDropSupport="true" auto="true" 
                                          sizeLimit="100000" allowTypes="/(\.|\/)(gif|jpe?g|png)$/" required="true" requiredMessage="Need image" update="growl"/>
                            <h:panelGrid columns="2" columnClasses="label, value">
                                <h:outputText value="Skip to last: " />
                                <h:selectBooleanCheckbox value="#{productController.skip}" />
                            </h:panelGrid>
                        </p:panel>
                    </p:tab>

                    <p:tab id="confirm" title="Confirmation">
                        <p:panel header="Confirmation">
                            <h:panelGrid id="confirmation" columns="3" columnClasses="grid,grid,grid">
                                <h:panelGrid columns="2" columnClasses="label, value">
                                    <p:outputLabel value="Product owner: " />
                                    <p:outputLabel value="#{productController.owner.user.firstName} #{productController.owner.user.surName}" />
                                    <p:outputLabel value ="Category: "/>
                                    <p:outputLabel value ="#{productController.selected.category}"/>
                                    <p:outputLabel value ="Productname: "/>
                                    <p:outputLabel value ="#{productController.selected.productName}"/>
                                    <p:outputLabel value ="ProductDescription: "/>
                                    <p:outputLabel value ="#{productController.selected.productDescription}"/>
                                    <p:outputLabel value ="Date created: "/>
                                    <p:outputLabel value ="#{productController.selected.createdDate}"/>
                                    <p:outputLabel value ="Start price: "/>
                                    <p:outputLabel value ="#{productController.selected.price}"/>
                                </h:panelGrid>
                                <p:commandLink>
                                    <p:graphicImage name="/images/productimg/#{productController.selected.pictureURL}"
                                               style="height: 200px"/>
                                </p:commandLink>
                            </h:panelGrid>
                            <p:commandButton value="Submit" actionListener="#{productController.create()}" process="@this"
                                             update="display,:ProductListForm:datalist,:growl" oncomplete="handleSubmit(args,'ProductCreateDialog');"
                                             />
                        </p:panel>
                    </p:tab>
                </p:wizard>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>

src/main/webapp/product/crud/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="ProductEditDlg" widgetVar="ProductEditDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.EditProductTitle}">
            <h:form id="ProductEditForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{productController.selected != null}">
                        <p:outputLabel value="#{bundle.EditProductLabel_id}" for="id" />
                        <p:inputText id="id" value="#{productController.selected.id}"  disabled="true" title="#{bundle.EditProductTitle_id}" required="true" requiredMessage="#{bundle.EditProductRequiredMessage_id}"/>
                        <p:outputLabel value="#{bundle.EditProductLabel_createdDate}" for="createdDate" />
                        <p:calendar id="createdDate" pattern="MM/dd/yyyy HH:mm:ss" disabled="true" value="#{productController.selected.createdDate}" title="#{bundle.EditProductTitle_createdDate}"/>
                       
                        
                        <p:outputLabel value="#{bundle.EditProductLabel_price}" for="price" />
                        <p:inputText id="price" value="#{productController.selected.price}" title="#{bundle.EditProductTitle_price}" />
                        <p:outputLabel value="#{bundle.EditProductLabel_productDescription}" for="productDescription" />
                        <p:inputTextarea id="productDescription" value="#{productController.selected.productDescription}" title="#{bundle.EditProductTitle_productDescription}" />
                        <p:outputLabel value="Product name" for="productname" />
                        <p:inputText id="productname" value="#{productController.selected.productName}" title="#{bundle.EditProductTitle_productname}" />
                        <p:outputLabel value="has picture" for="haspicture" />
                        <p:selectBooleanCheckbox id="haspicture" disabled="true" value="#{productController.selected.hasPicture}" />
                        <p:outputLabel value="#{bundle.EditProductLabel_auction}" for="auction" />
                        <p:selectOneMenu id="auction" value="#{productController.selected.auction}" disabled="true" >
                            <f:selectItem itemLabel="#{bundle.SelectOneMessage}"/>
                            <f:selectItems value="#{auctionController.itemsAvailableSelectOne}"
                                           var="auctionItem"
                                           itemValue="#{auctionItem}"/>
                        </p:selectOneMenu>
                        <p:outputLabel value="#{bundle.EditProductLabel_productPoster}" for="productPoster" />
                        <p:selectOneMenu id="productPoster" value="#{productController.selected.productPoster}" disabled="true" >
                            <f:selectItem itemLabel="#{bundle.SelectOneMessage}"/>
                            <f:selectItems value="#{customerController.itemsAvailableSelectOne}"
                                           var="productPosterItem"
                                           itemValue="#{productPosterItem}"/>
                        </p:selectOneMenu>
                        
                    </p:panelGrid>
                    <p:commandButton actionListener="#{productController.update}" value="#{bundle.Save}" update="display,:ProductListForm:datalist,:growl" oncomplete="handleSubmit(args, 'ProductEditDialog');"/>
                    <p:commandButton value="#{bundle.Cancel}" onclick="ProductEditDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>

src/main/webapp/product/crud/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="ProductViewDlg" widgetVar="ProductViewDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.ViewProductTitle}">
            <h:form id="ProductViewForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{productController.selected != null}">
                        <h:outputText value="#{bundle.ViewProductLabel_id}"/>
                        <h:outputText value="#{productController.selected.id}" title="#{bundle.ViewProductTitle_id}"/>
                        <h:outputText value="#{bundle.ViewProductLabel_category}"/>
                        <h:outputText value="#{productController.selected.category}" title="#{bundle.ViewProductTitle_category}"/>
                        <h:outputText value="#{bundle.ViewProductLabel_createdDate}"/>
                        <h:outputText value="#{productController.selected.createdDate}" title="#{bundle.ViewProductTitle_createdDate}">
                            <f:convertDateTime pattern="MM/dd/yyyy HH:mm:ss" />
                        </h:outputText>
                        <h:outputText value="#{bundle.ViewProductLabel_features}"/>
                        <h:outputText value="#{productController.selected.features}" title="#{bundle.ViewProductTitle_features}"/>
                        <h:outputText value="#{bundle.ViewProductLabel_pictureURL}"/>
                        <h:outputText value="#{productController.selected.pictureURL}" title="#{bundle.ViewProductTitle_pictureURL}"/>
                        <h:outputText value="#{bundle.ViewProductLabel_price}"/>
                        <h:outputText value="#{productController.selected.price}" title="#{bundle.ViewProductTitle_price}"/>
                        <h:outputText value="#{bundle.ViewProductLabel_productDescription}"/>
                        <h:outputText value="#{productController.selected.productDescription}" title="#{bundle.ViewProductTitle_productDescription}"/>
                        <h:outputText value="#{bundle.ViewProductLabel_productname}"/>
                        <h:outputText value="#{productController.selected.productName}" title="#{bundle.ViewProductTitle_productname}"/>
                        <h:outputText value="#{bundle.ViewProductLabel_haspicture}"/>
                        <p:selectBooleanCheckbox value="#{productController.selected.hasPicture}" disabled="true"/>
                        <h:outputText value="#{bundle.ViewProductLabel_auction}"/>
                        <h:outputText value="#{productController.selected.auction}" title="#{bundle.ViewProductTitle_auction}"/>
                        <h:outputText value="#{bundle.ViewProductLabel_productPoster}"/>
                        <h:outputText value="#{productController.selected.productPoster}" title="#{bundle.ViewProductTitle_productPoster}"/>
                        <h:outputText value="#{bundle.ViewProductLabel_bidCollection}"/>
                        <h:outputText value="here will come link for bid collection" title="#{bundle.ViewProductTitle_bidCollection}"/>
                    </p:panelGrid>
                    <p:commandButton value="#{bundle.Close}" onclick="ProductViewDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>