src/main/java/entities/Auction.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package entities;

import java.io.Serializable;
import java.util.Arrays;
import java.util.Date;
import java.util.List;
import java.util.Objects;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToOne;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import structures.AuctionLength;

/**
 *
 * @author alexa
 */
@Entity
@NamedQueries({
    @NamedQuery(name = "auction.findAllActiveAuctions", query = "SELECT a FROM Auction a where a.endAuction < :currentTime"),
    @NamedQuery(name = "auction.findAuctionByIdProduct", query = "SELECT a FROM Auction a where a.product.id = :productId"),
})
@XmlRootElement
public class Auction implements Serializable {

    private static final long serialVersionUID = 1L;
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;
    @Temporal(TemporalType.TIMESTAMP)
    Date startAuction;
    @Temporal(TemporalType.TIMESTAMP)
    Date endAuction;
    @OneToOne
    Bid currentBid;
    AuctionLength auctionLength;
    @Transient
    private boolean isActive; 
    @OneToOne
    @JoinColumn(name = "product_fk")
    private Product product;
    public boolean isIsActive() {
        if (endAuction !=null) {
        if (endAuction.after(new Date())) {
            return true;
        }
        }
        return isActive;
    }
    
    public Product getProduct() {
        return product;
    }

    public void setProduct(Product product) {
        this.product = product;
    }

    public AuctionLength getAuctionLength() {
        return auctionLength;
    }
    public List<AuctionLength> getAllAuctionLengths(){
        return Arrays.asList(AuctionLength.values());
    }

    public void setAuctionLength(AuctionLength auctionLength) {
        this.auctionLength = auctionLength;
    }

    public void setIsActive(boolean isActive) {
        this.isActive = isActive;
    }

    public Date getStartAuction() {
        return startAuction;
    }

    public void setStartAuction(Date startAuction) {
        this.startAuction = startAuction;
    }

    public Date getEndAuction() {
        if (endAuction == null) {
            endAuction = new Date();
        }
        return endAuction;
    }
    public String getEndAuctionSt(){
        if (endAuction == null) {
            return "is not started yet";
        }
        return endAuction.toString();
    }
    public void setEndAuction(Date EndAuction) {
        this.endAuction = EndAuction;
    }

    public Bid getCurrentBid() {
        return currentBid;
    }

    public void setCurrentBid(Bid currentBid) {
        this.currentBid = currentBid;
    }

    void setAuction(Date start, Date end, Product product) {
        startAuction = start;
        endAuction = end;
        this.product = product;
        isActive = true;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }
    public int convertIntoSeconds() {
        Date timeNow = new Date();
        long inSeconds = timeNow.getTime();

        if (endAuction != null) {
            long timeRemmaining = endAuction.getTime() - inSeconds;
            if (timeRemmaining > 0) {
                return Math.toIntExact(timeRemmaining);
            }
        }
        return 0;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 47 * hash + Objects.hashCode(this.id);
        hash = 47 * hash + Objects.hashCode(this.startAuction);
        hash = 47 * hash + Objects.hashCode(this.endAuction);
        hash = 47 * hash + Objects.hashCode(this.currentBid);
        hash = 47 * hash + Objects.hashCode(this.auctionLength);
        hash = 47 * hash + (this.isActive ? 1 : 0);
        hash = 47 * hash + Objects.hashCode(this.product);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Auction other = (Auction) obj;
        if (this.isActive != other.isActive) {
            return false;
        }
        if (!Objects.equals(this.id, other.id)) {
            return false;
        }
        if (!Objects.equals(this.startAuction, other.startAuction)) {
            return false;
        }
        if (!Objects.equals(this.endAuction, other.endAuction)) {
            return false;
        }
        if (!Objects.equals(this.currentBid, other.currentBid)) {
            return false;
        }
        if (this.auctionLength != other.auctionLength) {
            return false;
        }
        if (!Objects.equals(this.product, other.product)) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "Auction{" + "id=" + id /*+ ", startAuction=" + startAuction + ", endAuction=" + endAuction + ", currentBid=" + currentBid + ", auctionLength=" + auctionLength + ", isActive=" + isActive + ", product=" + product  */ +'}';
    }

   

    
}

src/main/java/mangedBeans/controller/AuctionController.java
package mangedBeans.controller;

import entities.Auction;
import Interfaces.util.JsfUtil;
import Interfaces.util.JsfUtil.PersistAction;
import boundary.AuctionFacade;
import boundary.CustomerFacade;
import entities.Customer;
import entities.Product;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.annotation.security.DeclareRoles;
import javax.ejb.EJB;
import javax.ejb.EJBException;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;

@Named("auctionController")
@SessionScoped
//@DeclareRoles({"admin","customer"})
public class AuctionController implements Serializable {

    @EJB
    private AuctionFacade af;
    @EJB
    private CustomerFacade cf;
    private List<Auction> items = null;
    private List<Auction> customerAuctions = null;
    private Auction selected;
    private long custId;
    private long prodId;

    public AuctionController() {
    }

    public long getProdId() {
        
        return prodId;
    }

    public void setProdId(long prodId) {
        this.prodId = prodId;
    }

    public long getCustId() {
        return custId;
    }

    public void setCustId(long custId) {
        this.custId = custId;
    }

    public List<Auction> getCustomerAuctions() {
        return customerAuctions;
    }

    public void setCustomerAuctions(List<Auction> customerAuctions) {
        this.customerAuctions = customerAuctions;
    }

    public Auction getSelected() {
        return selected;
    }

    public void setSelected(Auction selected) {
        this.selected = selected;
    }

    protected void setEmbeddableKeys() {
    }

    protected void initializeEmbeddableKey() {
    }

    private AuctionFacade getFacade() {
        return af;
    }

    public Auction prepareCreate() {
        selected = new Auction();
        initializeEmbeddableKey();
        return selected;
    }

    public void create() {
        persist(PersistAction.CREATE, ResourceBundle.getBundle("/Bundle").getString("AuctionCreated"));
        if (!JsfUtil.isValidationFailed()) {
            items = null;    // Invalidate list of items to trigger re-query.
        }
    }

    public void update() {
        persist(PersistAction.UPDATE, ResourceBundle.getBundle("/Bundle").getString("AuctionUpdated"));
    }

    public void destroy() {
        persist(PersistAction.DELETE, ResourceBundle.getBundle("/Bundle").getString("AuctionDeleted"));
        if (!JsfUtil.isValidationFailed()) {
            selected = null; // Remove selection
            items = null;    // Invalidate list of items to trigger re-query.
        }
    }

    public List<Auction> getItems() {
        if (items == null) {
            items = getFacade().findAll();
        }
        return items;
    }
    public String getCustomersAuctionItems(javax.faces.event.ActionEvent event){
        long id = (long) event.getComponent().getAttributes().get("customerId");
        customerAuctions = new ArrayList<>();
       List<Product> productList= cf.find(id).getProductList();
        if (productList !=null) {
            for (Product p : productList) {
                customerAuctions.add(p.getAuction());
            }
        }
        return "/crud/auction/List";
    }
    public List<Auction> getAuctionItemsFromCust(){
         Customer customer = cf.find(custId);
        
        if (customer !=null) {
            return customer.getAuctionList();
        }
        return new ArrayList<>();
    }

    private void persist(PersistAction persistAction, String successMessage) {
        if (selected != null) {
            setEmbeddableKeys();
            try {
                if (persistAction != PersistAction.DELETE) {
                    getFacade().edit(selected);
                } else {
                    getFacade().remove(selected);
                }
                JsfUtil.addSuccessMessage(successMessage);
            } catch (EJBException ex) {
                String msg = "";
                Throwable cause = ex.getCause();
                if (cause != null) {
                    msg = cause.getLocalizedMessage();
                }
                if (msg.length() > 0) {
                    JsfUtil.addErrorMessage(msg);
                } else {
                    JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
                }
            } catch (Exception ex) {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, null, ex);
                JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            }
        }
    }

    public Auction getAuction(java.lang.Long id) {
        return getFacade().find(id);
    }

    public List<Auction> getItemsAvailableSelectMany() {
        return getFacade().findAll();
    }

    public List<Auction> getItemsAvailableSelectOne() {
        return getFacade().findAll();
    }

    @FacesConverter(forClass = Auction.class)
    public static class AuctionControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            AuctionController controller = (AuctionController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "auctionController");
            return controller.getAuction(getKey(value));
        }

        java.lang.Long getKey(String value) {
            java.lang.Long key;
            key = Long.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Long value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Auction) {
                Auction o = (Auction) object;
                return getStringKey(o.getId());
            } else {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, "object {0} is of type {1}; expected type: {2}", new Object[]{object, object.getClass().getName(), Auction.class.getName()});
                return null;
            }
        }

    }

}

src/main/webapp/crud/auction/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="AuctionCreateDlg" widgetVar="AuctionCreateDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.CreateAuctionTitle}">
            <h:form id="AuctionCreateForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{auctionController.selected != null}">
                        <p:outputLabel value="#{bundle.CreateAuctionLabel_product}" for="product" />
                        <p:selectOneMenu id="product" value="#{auctionController.selected.product}" >
                            <f:selectItems value="#{productController.itemsAvailableSelectOne}"
                                           var="productItem"
                                           itemValue="#{productItem}"/>
                        </p:selectOneMenu>
                        <p:outputLabel value="#{bundle.CreateAuctionLabel_auctionLength}" for="auctionLength" />
                        <p:inputText id="auctionLength" value="#{auctionController.selected.auctionLength}" title="#{bundle.CreateAuctionTitle_auctionLength}" />
                        <p:outputLabel value="#{bundle.CreateAuctionLabel_startAuction}" for="startAuction" />
                        <p:calendar id="startAuction" pattern="MM/dd/yyyy HH:mm" value="#{auctionController.selected.startAuction}" title="#{bundle.EditAuctionTitle_startAuction}"  showOn="button"/>
                        <p:outputLabel value="#{bundle.CreateAuctionLabel_endAuction}" for="endAuction" />
                        <p:calendar id="endAuction" pattern="MM/dd/yyyy HH:mm" value="#{auctionController.selected.endAuction}" title="#{bundle.EditAuctionTitle_endAuction}"  showOn="button"/>
                        <p:outputLabel value="#{bundle.CreateAuctionLabel_endAuctionSt}" for="endAuctionSt" />
                        <p:inputText id="endAuctionSt" value="#{auctionController.selected.endAuctionSt}" title="#{bundle.CreateAuctionTitle_endAuctionSt}" />
                        <p:outputLabel value="#{bundle.CreateAuctionLabel_currentBid}" for="currentBid" />
                        <p:selectOneMenu id="currentBid" value="#{auctionController.selected.currentBid}" >
                            <f:selectItems value="#{bidController.itemsAvailableSelectOne}"
                                           var="currentBidItem"
                                           itemValue="#{currentBidItem}"/>
                        </p:selectOneMenu>
                        <p:outputLabel value="#{bundle.CreateAuctionLabel_id}" for="id" />
                        <p:inputText id="id" value="#{auctionController.selected.id}" title="#{bundle.CreateAuctionTitle_id}" />
                    </p:panelGrid>
                    <p:commandButton actionListener="#{auctionController.create}" value="#{bundle.Save}" update="display,:AuctionListForm:datalist,:growl" oncomplete="handleSubmit(args,'AuctionCreateDialog');"/>
                    <p:commandButton value="#{bundle.Cancel}" onclick="AuctionCreateDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>

src/main/webapp/crud/auction/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="AuctionEditDlg" widgetVar="AuctionEditDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.EditAuctionTitle}">
            <h:form id="AuctionEditForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{auctionController.selected != null}">
                        <p:outputLabel value="#{bundle.EditAuctionLabel_product}" for="product" />
                        <p:selectOneMenu id="product" value="#{auctionController.selected.product}" >
                            <f:selectItem itemLabel="#{bundle.SelectOneMessage}"/>
                            <f:selectItems value="#{productController.itemsAvailableSelectOne}"
                                           var="productItem"
                                           itemValue="#{productItem}"/>
                        </p:selectOneMenu>
                        <p:outputLabel value="#{bundle.EditAuctionLabel_auctionLength}" for="auctionLength" />
                        <p:inputText id="auctionLength" value="#{auctionController.selected.auctionLength}" title="#{bundle.EditAuctionTitle_auctionLength}" />

                        <p:outputLabel value="#{bundle.EditAuctionLabel_startAuction}" for="startAuction" />
                        <p:calendar id="startAuction" pattern="MM/dd/yyyy HH:mm:ss" value="#{auctionController.selected.startAuction}" title="#{bundle.EditAuctionTitle_startAuction}"  showOn="button"/>
                        <p:outputLabel value="#{bundle.EditAuctionLabel_endAuction}" for="endAuction" />
                        <p:calendar id="endAuction" pattern="MM/dd/yyyy HH:mm:ss" value="#{auctionController.selected.endAuction}" title="#{bundle.EditAuctionTitle_endAuction}"  showOn="button"/>
                        <p:outputLabel value="#{bundle.EditAuctionLabel_currentBid}" for="currentBid" />
                        <p:selectOneMenu id="currentBid" value="#{auctionController.selected.currentBid}" >
                            <f:selectItem itemLabel="#{bundle.SelectOneMessage}"/>
                            <f:selectItems value="#{bidController.itemsAvailableSelectOne}"
                                           var="currentBidItem"
                                           itemValue="#{currentBidItem}"/>
                        </p:selectOneMenu>
                        <p:outputLabel value="#{bundle.EditAuctionLabel_id}" for="id" />
                        <p:inputText id="id" value="#{auctionController.selected.id}" title="#{bundle.EditAuctionTitle_id}" />
                    </p:panelGrid>
                    <p:commandButton actionListener="#{auctionController.update}" value="#{bundle.Save}" update="display,:AuctionListForm:datalist,:growl" oncomplete="handleSubmit(args, 'AuctionEditDialog');"/>
                    <p:commandButton value="#{bundle.Cancel}" onclick="AuctionEditDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>

src/main/webapp/crud/auction/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition template="/templates/common/template.xhtml">


        <ui:define name="title">
            <h:outputText value="#{bundle.ListAuctionTitle}"></h:outputText>
            <h:outputStylesheet name="css/jsfcrud.css"/>
        <h:outputStylesheet library="css" name="style.css"/>
        </ui:define>


        <ui:define name="body">
            <f:metadata>
                <f:viewParam name="userId" value="#{auctionController.custId}"/>
            </f:metadata>
           
            <h:form id="AuctionListForm">
                <p:panel header="#{bundle.ListAuctionTitle}">
                    <p:dataTable id="datalist" value="#{auctionController.auctionItemsFromCust}" var="item"
                                 selectionMode="single" selection="#{auctionController.selected}"
                                 paginator="true"
                                 rowKey="#{item.id}"
                                 rows="10"
                                 rowsPerPageTemplate="10,20,30,40,50"
                                 >

                        <p:ajax event="rowSelect"   update="createButton viewButton editButton deleteButton"/>
                        <p:ajax event="rowUnselect" update="createButton viewButton editButton deleteButton"/>

                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ProductOwner}"/>
                            </f:facet>
                            <h:outputText value="#{item.product.productPoster.uname}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListAuctionTitle_product}"/>
                            </f:facet>
                            <h:outputText value="#{item.product}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListAuctionTitle_auctionLength}"/>
                            </f:facet>
                            <h:outputText value="#{item.auctionLength}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListAuctionTitle_allAuctionLengths}"/>
                            </f:facet>
                            <h:outputText value="#{item.allAuctionLengths}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListAuctionTitle_startAuction}"/>
                            </f:facet>
                            <h:outputText value="#{item.startAuction}">
                                <f:convertDateTime pattern="MM/dd/yyyy HH:mm" />
                            </h:outputText>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListAuctionTitle_endAuction}"/>
                            </f:facet>
                            <h:outputText value="#{item.endAuction}">
                                <f:convertDateTime pattern="MM/dd/yyyy HH:mm" />
                            </h:outputText>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListAuctionTitle_endAuctionSt}"/>
                            </f:facet>
                            <h:outputText value="#{item.endAuctionSt}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListAuctionTitle_currentBid}"/>
                            </f:facet>
                            <h:outputText value="#{item.currentBid}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListAuctionTitle_id}"/>
                            </f:facet>
                            <h:outputText value="#{item.id}"/>
                        </p:column>
                        <f:facet name="footer">
                            <p:commandButton id="createButton" icon="ui-icon-plus"   value="#{bundle.Create}" actionListener="#{auctionController.prepareCreate}" update=":AuctionCreateForm" oncomplete="PF('AuctionCreateDialog').show()"/>
                            <p:commandButton id="viewButton"   icon="ui-icon-search" value="#{bundle.View}" update=":AuctionViewForm" oncomplete="PF('AuctionViewDialog').show()" disabled="#{empty auctionController.selected}"/>
                            <p:commandButton id="editButton"   icon="ui-icon-pencil" value="#{bundle.Edit}" update=":AuctionEditForm" oncomplete="PF('AuctionEditDialog').show()" disabled="#{empty auctionController.selected}"/>
                            <p:commandButton id="deleteButton" icon="ui-icon-trash"  value="#{bundle.Delete}" actionListener="#{auctionController.destroy}" update=":growl,datalist" disabled="#{empty auctionController.selected}"/>
                        </f:facet>
                    </p:dataTable>
                </p:panel>
            </h:form>

            <ui:include src="Create.xhtml"/>
            <ui:include src="Edit.xhtml"/>
            <ui:include src="View.xhtml"/>
        </ui:define>
    </ui:composition>

</html>

src/main/webapp/crud/auction/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="AuctionViewDlg" widgetVar="AuctionViewDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.ViewAuctionTitle}">
            <h:form id="AuctionViewForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{auctionController.selected != null}">
                        <h:outputText value="#{bundle.ViewAuctionLabel_product}"/>
                        <h:outputText value="#{auctionController.selected.product}" title="#{bundle.ViewAuctionTitle_product}"/>
                        <h:outputText value="#{bundle.ViewAuctionLabel_auctionLength}"/>
                        <h:outputText value="#{auctionController.selected.auctionLength}" title="#{bundle.ViewAuctionTitle_auctionLength}"/>
                        <h:outputText value="#{bundle.ViewAuctionLabel_allAuctionLengths}"/>
                        <h:outputText value="#{auctionController.selected.allAuctionLengths}" title="#{bundle.ViewAuctionTitle_allAuctionLengths}"/>
                        <h:outputText value="#{bundle.ViewAuctionLabel_startAuction}"/>
                        <h:outputText value="#{auctionController.selected.startAuction}" title="#{bundle.ViewAuctionTitle_startAuction}">
                            <f:convertDateTime pattern="MM/dd/yyyy HH:mm:ss" />
                        </h:outputText>
                        <h:outputText value="#{bundle.ViewAuctionLabel_endAuction}"/>
                        <h:outputText value="#{auctionController.selected.endAuction}" title="#{bundle.ViewAuctionTitle_endAuction}">
                            <f:convertDateTime pattern="MM/dd/yyyy HH:mm:ss" />
                        </h:outputText>
                        <h:outputText value="#{bundle.ViewAuctionLabel_endAuctionSt}"/>
                        <h:outputText value="#{auctionController.selected.endAuctionSt}" title="#{bundle.ViewAuctionTitle_endAuctionSt}"/>
                        <h:outputText value="#{bundle.ViewAuctionLabel_currentBid}"/>
                        <h:outputText value="#{auctionController.selected.currentBid}" title="#{bundle.ViewAuctionTitle_currentBid}"/>
                        <h:outputText value="#{bundle.ViewAuctionLabel_id}"/>
                        <h:outputText value="#{auctionController.selected.id}" title="#{bundle.ViewAuctionTitle_id}"/>
                    </p:panelGrid>
                    <p:commandButton value="#{bundle.Close}" onclick="AuctionViewDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>